version: '3'
services:

    db:
        image: mariadb:10.1.39
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=true
            - MYSQL_USER=s_user
            - MYSQL_PASSWORD=dbpassword
            - MYSQL_DATABASE=s_user__wudele
        restart: always
        ports:
            - "3307:3306"

    smtp:
        image: jeanberu/mailcatcher
        ports:
            - "1080:1080"

    web:
        build:
            dockerfile: conf/Dockerfile
            context: .
        depends_on:
            - db
        environment:
            - ENV=dev
            - APACHE_RUN_USER=#1000
            - DB_HOST=db
            - MAIL_HOST=smtp
            - MAIL_PORT=1025
        restart: always
        ports:
            - 8000:80
        volumes:
            - ./files/MailService.php:/var/www/html/wudele/app/classes/Framadate/Services/MailService.php
            - ./files/config.php:/var/www/html/wudele/app/inc/config.php
            - ./files/locale/en.json:/var/www/html/wudele/locale/en.json
            - ./files/locale/de.json:/var/www/html/wudele/locale/de.json
            - ./conf/variables.php:/var/www/html/wudele/app/inc/variables.php
            - ./conf/my.cnf:/my.cnf
            - ./files/logo-wudele.png:/var/www/html/wudele/images/logo-wudele.png
            - ./logs/:/var/www/html/wudele/logs/
