version: '3'
services:

    db:
        image: mariadb:10.0
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=true
            - MYSQL_USER=s_user
            - MYSQL_PASSWORD=dbpassword
            - MYSQL_DATABASE=s_user__wudele
        restart: always
        ports:
            - "3307:3306"

    web:
        build:
            dockerfile: conf/Dockerfile
            context: .
        depends_on:
            - db
        environment:
            - ENV=dev
            - APACHE_RUN_USER=#1000
            - DB_HOST=db
        restart: always
        ports:
            - 8000:80
