---
- hosts: toolforge
  gather_facts: false

  vars:
    database_config_file: '{{ base_path }}/replica.my.cnf'

  tasks:

    - import_tasks: tasks/database.yml
      tags: database

    - import_tasks: tasks/application-install.yml
      tags: application-install
      vars:
        src_path: "{{ base_path }}/src"

    - import_tasks: tasks/application-config.yml
      tags: application-config
      vars:
        src_path: "{{ base_path }}/src"
        app_path: "{{ src_path }}/vendor/framasoft/framadate"
