- name: Alter get_server_name to avoid wrong port detection
  lineinfile:
    path: "{{ app_path }}/app/classes/Framadate/Utils.php"
    state: present
    regexp: '^(\s+\$port\s+=)'
    line: \1 '';
    backrefs: true
    validate: php -l %s

# https://framagit.org/framasoft/framadate/framadate/-/issues/363
- name: Patch locale for expiration date
  copy:
    src: "{{ item }}"
    dest: "{{ app_path }}/locale/"
    validate: python -m json.tool %s
  with_fileglob:
    - "files/locale/*.json"
