- name: Symlink cnf file
  file:
    src: '{{ database_config_file }}'
    path: '{{ base_path }}/{{ item }}'
    state: link
  with_items:
    - 'database.fact'
  tags:
    - paths
  register: database_configuration

- name: Collect facts
  setup:
    fact_path: "{{ base_path }}"
    gather_subset: "!all"

- name: Create database
  mysql_db:
    name: "{{ ansible_local['database']['client']['user'] }}__wudele"
    state: present
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
    login_host: tools.db.svc.eqiad.wmflabs
    config_file: '{{ database_config_file }}'
  register: database
  tags:
    - db